#+OPTIONS: H:1
#+SETUPFILE: setup.xorg
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [koma,b5paper,oneside,notitlepage]
#+LATEX_HEADER: \usepackage{indentfirst}
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage[adobe-utopia]{mathdesign}
#+LATEX_HEADER: \usepackage[scaled]{berasans}
#+LATEX_HEADER: \usepackage[scaled]{beramono}
#+LATEX_HEADER: \setlength{\parskip}{1mm}

* Episode 1

*stamp* *stamp* *stamp*
*stamp* *stamp*

"Feliz cumpleanos", said the border agent to Laura, as he returned
all the passports in a pile and handed them to Dad, who set about
collating the immigration cards and sorting them among the family.

Ophelia (age: 12 - citizenship - United States - place of birth -
Pennsylvania) twirled around *twice* and held the little blue passport
(issuing authority - US Department of State) high in the air.

"Ophelia Biliski, citizen... of the /world/."

"Citizen of /crazy-town/ is more like it," observed her brother Randy.

"Please, please," said Laura. "She said citizen of the world. Isn't
that just redundant?"

"... Point."

-----

"I can't find my [[https://www.youtube.com/watch?v=P-bz4kRtCQI][Scott Hahn]] tape,"
observed Mom.

"I think I put it in the big luggage."

"Oh thank GOD." said Randy.

"We'll sort through it later," said Dad.

"Hey. I don't mind the Scott Hahn talks," said Ophelia.

"Well aren't you a little miss goody two-shoes," said Randy."

"Hey. HEY. It's just not right to call your sister names like that."
said Laura.

"Are you kidding? She's like the most -"

"No, I mean, /miss goody two-shoes/ is structurally wrong. It's two
forms of address. Either she's [[https://www.youtube.com/watch?v=P-bz4kRtCQI][Goodwife Two-Shoes]], or Mistress
Two-Shoes, but both at once is just /incorrect/."

"It's redundant." noted Ophelia.

"... As you wish, Princess Two-Shoes."

"I've got some stuff we could listen to on my phone," offered Laura.

"... I don't think your mother really cares for most of your music."
noted Dad.

"Mmf." mumbled Mom, leaning against a window, trying not to be carsick.

"I have, somwhere..." said Rose, fiddling with the device, "... aha!
Here we go. Vintage radio drama."

"Blagh." opined Randy.

"Vintage radio /crime/ drama."

"You have my attention!" recanted the boy.

"Who knows what evil lurks in the hearts of man? Heh heh heh heh
heh... [[https://www.youtube.com/watch?v=q061NWVbj-Q][the Shadow knows!]]" intoned the car radio.


-----

They'd run out of vintage radio crime drama, and were bouncing along
the highway singing a capella.

"Boys may come, and boys may go, and that's all right, you see," wailed
Laura, channeling [[https://youtu.be/e3wYIjI8WcI?t=185][Madonna]].

"liv. ing. in a mat erial world," chanted Randy in his most
 robotic impersonation of a backup singer.

"Great," complained Mom, still feeling a bit carsick. "We haul you all
the way to Mexico so you can sing the worst of American pop."

"Would you prefer ... mariachi?" inquired Randy, flatly.

"/Yo no puedo mariachi. No hablamos tan mas de Espanol/", objected
Ophelia.

"Yeah, yo no hablaminos... Foreign languages are hard," said
Randy. "Music is even harder."

"Actually, I think the songs make it easier to learn."

"Sure, I guess," said Randy, "if you mean like [[https://www.youtube.com/watch?v=s6qRMHpV7Pc][Pescador de Hombres]] or
something that Mom always plays."

"We should watch more shows together," proposed Ophelia. "Television
is also a great way to learn, especially with captions."

"What television do you ... wait. Wait, NO!"

Ophelia beamed. "You can pick up all sorts of useful Japanese phrases
watching magical girl shows."

"Me think /snot/," said Randy.

"I want to take Japanese once I get to high school so I can do a
semester abroad in college."

"OooOoh, somebody's got /life plans/. Good for youuu," said the little
brother.

"I am thoroughly in agreement with these life plans," said Laura, "and
magical girl shows supply so many ever-so-useful phrases.
'/Sayonara, Homura-chan! Genki de ne!/'"
She placed her hand over her heart, passionately.

"... That's... I don't think I've seen that show." noted Ophelia.

"Well, you NEED to!" said Laura. "It's basically the bestest."

"No, you two are the bestest! [[https://www.youtube.com/watch?v=uDgx8r4cbeU][Dai dai daisuki!]]" smiled Ophelia,
hugging them both, one on either side. She leaned her head over to
nuzzle her cheek up against Randy's.

"Mom! Dad! She's smiling on me! Make her stop."

Dad cleared his throat. "[[https://youtu.be/tsxVGb2d9dw?t=98][Come on, people now.]]"

"Aaaaaaaarrrrrrrrggggggggggggghhhhhhh!"

"Okay, here's one you might appreciate right now,"
offered Laura. '[[https://www.youtube.com/watch?v=R229aaDg3Gk][Urusai, urusai, urusai!]]'"

"Here's one for you: /Bwaaaaaaaarrrrrrrrrrrrgh/."

"Uh huh. And who is that quoting?" enquired Laura.

"Duh. Godzilla."

-----

"We should just stop at one of those guys selling street food," said
Randy, "and eat in the car."

"Not in a rental car, thank you," said Dad. "I'm not paying a hundred
dollars cleaning fee."

"Well then, we can stand outside in the shade somewhere."

"Randy. You know what Mom would say. [[https://youtu.be/lC2u_24kdCg?t=42][You don't have to eat like a
refugee]]." observed Ophelia.

"THIS ONE!" said Mom. "Stop here! It's got a Virgin of Guadalupe in
front. Ha ha!"

"Mom," noted Laura, "this... is Mexico. That... is a tacqueria. They
/all/ have the Virgin of Guadalupe somewhere."

"Yeah, well, this one has it in front, and I saw it! We're stopping
here. We're stopping here!!" sang Mom.

Dad parked the car.

"Ah, /Mexico/," said Randy. He said it in a stylized way, "May-hi-co",
a self-aware gringo's rendition of the accent.

"Ah, Mom." said Ophelia.

"Ophelia," said Laura. "/Mi madre... es su madre./"

"Uuuuuuurrrgh," said Randy, failing to surpress his
laugh. "No. No. Whyyyyy?"

Inside, Mom considered the menu.

"So what's everyone getting?" asked Dad.

"I have an idea," offered Randy. "/Mexican./"

"Churros?" inquired Ophelia.

"Tacos," said Mom.

"Burritos," suggested Laura.

"You know that -ito is just... what do you call it... a diminutive,
right?" asked Randy.

"Si si, Randito," said Ophelia.

"Never mind /Randito/. The food."

"What about the food?"

"Burritos. Burros. You're going to eat /little donkeys/."

"Hey, I like donkeys," said Mom. "They're gentle creatures."

"Ah, Mom." said Ophelia.

"Oh, hey," said Laura. "We could get /tequila shots/."

"We are not getting tequila shots," said Mom.

"Actually, maybe you should. She might swear off alcohol for life,"
proposed Dad.

-----

"Are we there yet?" asked Randy, as they got into the car.

"Another hour and a bit," said Dad.

"Don't worry!" said Mom, holding aloft a CD. "I haven't found Scott
Hahn but I *have* found some music!"

"What? ... Wait - nooooooooooo!" cried Randy.

"Hey. I don't mind Mom's music." said Ophelia.

"Well, good for you," snapped Randy.

"Randy," cautioned Dad, "I'll thank you to show a little respect to
your sister, /and/ your mother." He placed the CD in the car.

"It's /objectively terrible./ It's like... three-chord rock and roll,
but without any of the rock, or the roll."

"Actually," offered Ophelia, "there's a really nice circle of fifths
in the third --"

"I don't caaaaaaaaaare." said Randy.

"Good. You don't care. When the fire falls from the heavens on
Judgement Day you can tell Saint Michael, in detail, all about how you
don't care." said Mom.

"Randolph," said Dad, turning off the car.

"What?"

"See over there by the overpass?"

"What, the bus stop?"

"If you'd rather not ride with us, you can take a /collectivo/. Tell
the driver you want Cenote Pacifico." He started to take out his
wallet. "Will you pass me the phrase-book, dear?"

It was very quiet, for more than a moment.

"That's what I thought," said Dad, starting the car again.

Mom played her CD.

No one said much of anything for a few minutes.

"[[https://youtu.be/D4hXJ9ax2FY?t=36][Send forth your word]]", said the CD, "Lord, and let there be light!"

/braaaaaaaaaaaaaaap/, went a noise.

"/Randy/." said Dad.

"I'm sorry, Dad, that was me." interjected Ophelia.

"Wooh, ugh." said Mom. "Beans!"

Ophelia looked embarrassed.

"No one /ever/ suspects Goodwife Two-Shoes," said Laura.

"Pull over, I think I'm going to be sick." said Mom.

Dad pulled over, and rolled down the windows.

Mom sat a while. The /song/ part of the praise and worship tape faded
into a sort of a prayerful coda. "Let mercy triumph over judgment,"
said the voice on the CD.

-----

"This is the place?" asked Ophelia.

"Sweatness!" exclaimed Laura.

"... sweatness?" asked Mom.

"Yeah. It's like saying /sweetness/, but ... hotter."

"Thank you for that... /vivid/ interjection," said Randy, still a
little subdued.

"Anytime, bro."

Randy looked around. "I don't see the beach," he noted flatly.

"We don't have a place on the beach." said Dad. "We have the nicest
place that's willing to give us a free stay while trying to convince
us to buy a timeshare."

"Watch the car for a moment," said Mom to Laura, "I'm going in to
powder my nose."

A moment passed to the 'tink. tink. tink.' sounds of a cooling engine
block.

"Thanks for, uh, covering for me," said Randy to Ophelia.

"/Randito mio/... it's like they say. /Mi madre es su madre./" offered
Ophelia.

"Yeah. It's true." said Randy. "It's true."

-----

"Cooooool." Randy gazed over the edge of a railing into the rather
large, elegantly furnished hole in the ground.

"Aquí es ... Cenote Pacifico," said Laura.

"It /is/ cool. It's connected to underground caves!" said Ophelia.

"Mmm. Natural air conditioning. I like." opined Randy.

"And it's got /shade/, so I can swim around, without turning into a
lobster!"

"Yeah, well, it's not my fault you're so..."

"White?"

"I was gonna say /Slavic/," said Randy.

"Ah. Mom's fault."

"Mmm, yes, Parental Unit Number 2."

"Parental unit ... nevermind." said Laura.

Mom was a few steps behind coming out of the lobby. "Okay, here we
go. I brought one for everybody."

"Brought one what?" asked Randy, as mom handed him a small bottle.
".... Holy water?"

"The cenote is supposed to be a portal to the /underworld./ I'm not
letting any of my children play around in a portal to the underworld
unless you bless yourself /first/. Basic parenting."

"Oh god she's serious", mumbled Randy.

"Uhh..." said Laura...

"Every time you go in," said Mom.

"Okay, I promise." said Ophelia, extracting a few drops. "I'll do it
right now."

"Mmmm. Exactly as one would expect from Princess Two-Shoes", noted
Randy.

"It won't hurt you," noted Ophelia.

"[[https://www.youtube.com/watch?v=ap_mEm8m0HU][It burnssssss us!]]" emoted Randy.


"Please, Smeagol. You've been with us how many years? If holy water
/actually/ hurt you in /any/ way, you'd have died a long, long time
ago," said Ophelia.

"Maybe I /am/ dead, and this is all just my trip to the underworld,"
suggested Randy, pointing to the cenote.

"Hmmbly," pondered Laura. "That's as good an explanation as any."

"Hey, Parental Unit 1," asked Randy, "can we go to Chicken Itza?"

"Chicken?" inquired Ophelia.

"We are not going to Chichen Itza," declared Mom.

"We're not? Would you deny our children the sight of one of the
Wonders of the World?" asked Dad, as he unlocked the room.

"Yes," declared Mom, without a moment's hesitation. "We're not here
for cultural exchange with a civilization of bloodthirsty pagans,
we're here to /relax/. Besides which, it's a four hour drive, and
I don't feel like being carsick the whole way."

"Bloodthirsty pagans," said Laura, rolling her eyes. "Gee. Tell us how
you /really/ feel."

"You know, it won't hurt you children to start caring about your own
souls for once," said Mom. "That goes double for you, little miss I'm
Eighteen Now."

"Okay, enough," interrupted Dad, loudly. "How about we figure out
rooms and relax for a bit? I'm sure we're all tired and a little
cranky."

-----

"It's still not fair that I have to sleep on the couch," complained
Randy.

"Yeah, well, you get your own room at home, you can deal with a little
inconvenience now and then," retorted Laura.

"Actually, I'm going to miss sharing with you," said Ophelia to her
sister.

"Awwwwwww," said Laura, smiling on Ophelia. "That's just 'cuz you're
so sweet."

"'Beautiful cinnamon roll too good for this world, too pure,'"
quoted Randy.

"'Look at this angelic confection!'" said Laura.

"I think you have me confused with an Onion," objected Ophelia.

"Hey Laura. When you're done smiling on your sister," said Mom, "we
can order birthday drinks."

"OooooOooOoooh," said Laura.

"Are you sure that's a good idea?" asked Dad.

"My plan is to spoil her rotten with the /good/ stuff so she'll be too
much of a liquor snob to drink anything at big campus parties," said
Mom.

"This is a silly plan," noted Laura. "I think I approve."

Dad rolled his eyes. "I think I'd best leave you /girls/ to girl
stuff."

"Same," sighed Randy. "Enjoy the corn squeezin's for me."

"But Randito, /you're/ the corniest one around," noted Laura, reaching
out for a hug.

-----

The waiter visited the table. "Another drink for you, señorita?"

"You're sure you haven't had too much?" asked Ophelia.

"We're not as think as you drunk we am," retorted Laura.

"I told you this would be better than tequila shots," said Mom.

Laura pointed to a spot on the drink menu. "How about this one?"

"I think I'll leave you guys to your booze," said Dad.

"Glorious," remarked Randy. "I'll come with."

"You all are no fun," said Laura.

The waiter left with the order.

"What did you get?" asked Mom, looking at the menu. "Wait... cinnamon?
In a cocktail??"

-----

"Blegh!" said Laura. She put down the cocktail glass.

"Told you so," said Mom.

"I /like/ cimmanum," said Ophelia, "but it's not really authentic and
Mexican. Now, really bitter chocolate, sure..."

"Never mind that," said Laura, dismissively. "I think I'm feeling
kinda... queasy."

"Are you all right?" asked Mom.

"Mmmaybe a little wobbly," said Laura. "Donde están un baños?"

"/Los baños/," corrected Ophelia. "It's in California, about halfway
up."

"You know what I mean," snapped Laura.

"Right," said Mom. "Ophelia, can you watch the stuff a moment? Your
sister may be thinker than she thought she was."

"Okay, Mom," replied Ophelia, as the pair disappeared.

Ophelia waited quietly for a moment, pondering. This corner of the dining
area was pretty empty, wasn't it? She looked for the waiter. He was
busy on the other side of the restaurant.

She looked to the left.

She looked to the right.

Then she picked up the cocktail glass, with the care and attention one
might pay to a holy relic.

"Nobody /ever/ suspects the goodwife Two-Shoes," declared the girl to
herself, quietly.

The waiter had cleared off the table before Mom got back.
