#+OPTIONS: H:4
#+AUTHOR: nekosensei
#+TITLE: Revolutionary Ballerina Lyrical Ahiru
#+OPTIONS: html-postamble:nil
#+OPTIONS: date:nil creator:nil
#+OPTIONS: num:nil
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [koma,b5paper,oneside,notitle]
#+LATEX_HEADER: \usepackage{indentfirst}
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage[adobe-utopia]{mathdesign}
#+LATEX_HEADER: \usepackage[scaled]{berasans}
#+LATEX_HEADER: \usepackage[scaled]{beramono}
#+LATEX_HEADER: \setlength{\parskip}{1mm}

* Episode One



*stamp* *stamp* *stamp*
*stamp* *stamp*

"/Feliz cumpleanos/," said the border agent to Laura, as he returned
all the passports in a pile and handed them to Dad, who set about
collating the immigration cards and sorting them among the family.

"Ophelia Biliski, citizen... of the /world/."

Ophelia (age: 12 - citizenship - United States - place of birth -
Pennsylvania) twirled around /twice/ and held the little blue passport
(issuing authority - US Department of State) high in the air.

"Citizen of /crazy-town/ is more like it," observed her brother Randy.

"Please, please," said Laura. "She said citizen of the world. Isn't
that just redundant?"

"... Point."

-----

"I can't find my [[https://www.youtube.com/watch?v=P-bz4kRtCQI][Scott Hahn]] tape,"
observed Mom.

"I think I put it in the big luggage."

"Oh thank /god/." said Randy.

"We'll sort through it later," said Dad.

"Hey. I don't mind the Scott Hahn talks," said Ophelia.

"Well aren't you a little miss goody two-shoes," said Randy."

"Hey. HEY. It's just not right to call your sister names like that."
said Laura.

"Are you kidding? She's like the most -"

"No, I mean, /miss goody two-shoes/ is structurally wrong. It's two
forms of address. Either she's [[https://www.youtube.com/watch?v=P-bz4kRtCQI][Goodwife Two-Shoes]], or Mistress
Two-Shoes, but both at once is just /incorrect/."

"It's redundant." noted Ophelia.

"... As you wish, Princess Two-Shoes."

"I've got some stuff we could listen to on my phone," offered Laura.

"... I don't think your mother really cares for most of your music."
noted Dad.

"Mmf." mumbled Mom, leaning against a window, trying not to be carsick.

"I have, somwhere..." said Rose, fiddling with the device, "... aha!
Here we go. Vintage radio drama."

"Blagh." opined Randy.

"Vintage radio /crime/ drama."

"You have my attention!" recanted the boy.

"Who knows what evil lurks in the hearts of man? Heh heh heh heh
heh... [[https://www.youtube.com/watch?v=q061NWVbj-Q][the Shadow knows!]]" intoned the car radio.


-----

They'd run out of vintage radio crime drama, and were bouncing along
the highway singing a capella.

"Boys may come, and boys may go, and that's all right, you see," wailed
Laura, channeling [[https://youtu.be/e3wYIjI8WcI?t=185][Madonna]].

"liv. ing. in a mat erial world," chanted Randy in his most
 robotic impersonation of a backup singer.

"Great," complained Mom, still feeling a bit carsick. "We haul you all
the way to Mexico so you can sing the worst of American pop."

"Would you prefer ... mariachi?" inquired Randy, flatly.

"/Yo no puedo mariachi. No hablamos tan mas de Espanol/", objected
Ophelia.

"Yeah, yo no hablaminos... Foreign languages are hard," said
Randy. "Music is even harder."

"Actually, I think the songs make it easier to learn."

"Sure, I guess," said Randy, "if you mean like [[https://www.youtube.com/watch?v=s6qRMHpV7Pc][Pescador de Hombres]] or
something that Mom always plays."

"We should watch more shows together," proposed Ophelia. "Television
is also a great way to learn, especially with captions."

"What television do you ... wait. Wait, NO!"

Ophelia beamed. "You can pick up all sorts of useful Japanese phrases
watching magical girl shows."

"Me think /snot/," said Randy.

"I want to take Japanese once I get to high school so I can do a
semester abroad in college."

"OooOoh, somebody's got /life plans/. Good for youuu," said the little
brother.

"I am thoroughly in agreement with these life plans," said Laura, "and
magical girl shows supply so many ever-so-useful phrases.
'/Sayonara, Homura-chan! Genki de ne!/'"
She placed her hand over her heart, passionately.

"... That's... I don't think I've seen that show." noted Ophelia.

"Well, you NEED to!" said Laura. "It's basically the bestest."

"No, you two are the bestest! [[https://www.youtube.com/watch?v=uDgx8r4cbeU][Dai dai daisuki!]]" smiled Ophelia,
hugging them both, one on either side. She leaned her head over to
nuzzle her cheek up against Randy's.

"Mom! Dad! She's smiling on me! Make her stop."

Dad cleared his throat. "[[https://youtu.be/tsxVGb2d9dw?t=98][Come on, people now.]]"

"Aaaaaaaarrrrrrrrggggggggggggghhhhhhh!"

"Okay, here's one you might appreciate right now,"
offered Laura. '[[https://www.youtube.com/watch?v=R229aaDg3Gk][Urusai, urusai, urusai!]]'"

"Here's one for you: /Bwaaaaaaaarrrrrrrrrrrrgh/."

"Uh huh. And who is that quoting?" enquired Laura.

"Duh. Godzilla."

-----

"We should just stop at one of those guys selling street food," said
Randy, "and eat in the car."

"Not in a rental car, thank you," said Dad. "I'm not paying a hundred
dollars cleaning fee."

"Well then, we can stand outside in the shade somewhere."

"Randy. You know what Mom would say. [[https://youtu.be/lC2u_24kdCg?t=42][You don't have to eat like a
refugee]]." observed Ophelia.

"/This one!/" said Mom. "Stop here! It's got a Virgin of Guadalupe in
front. Ha ha!"

"Mom," noted Laura, "this... is Mexico. That... is a tacqueria. They
/all/ have the Virgin of Guadalupe somewhere."

"Yeah, well, this one has it in front, and I saw it! We're stopping
here. We're stopping here!!" sang Mom.

Dad parked the car.

"Ah, /Mexico/," said Randy. He said it in a stylized way, "May-hi-co",
a self-aware gringo's rendition of the accent.

"Ah, Mom." said Ophelia.

"Ophelia," said Laura. "/Mi madre... es su madre./"

"Uuuuuuurrrgh," said Randy, failing to surpress his
laugh. "No. No. Whyyyyy?"

Inside, Mom considered the menu.

"So what's everyone getting?" asked Dad.

"I have an idea," offered Randy. "/Mexican./"

"Churros?" inquired Ophelia.

"Tacos," said Mom.

"Burritos," suggested Laura.

"You know that -ito is just... what do you call it... a diminutive,
right?" asked Randy.

"Si si, Randito," said Ophelia.

"Never mind /Randito/. The food."

"What about the food?"

"Burritos. Burros. You're going to eat /little donkeys/."

"Hey, I like donkeys," said Mom. "They're gentle creatures."

"Ah, Mom." said Ophelia.

"Oh, hey," said Laura. "We could get /tequila shots/."

"We are not getting tequila shots," said Mom.

"Actually, maybe you should. She might swear off alcohol for life,"
proposed Dad.

-----

"Are we there yet?" asked Randy, as they got into the car.

"Another hour and a bit," said Dad.

"Don't worry!" said Mom, holding aloft a CD. "I haven't found Scott
Hahn but I /have/ found some music!"

"What? ... Wait - nooooooooooo!" cried Randy.

"Hey. I don't mind Mom's music." said Ophelia.

"Well, good for you," snapped Randy.

"Randy," cautioned Dad, "I'll thank you to show a little respect to
your sister, /and/ your mother." He placed the CD in the car.

"It's /objectively terrible./ It's like... three-chord rock and roll,
but without any of the rock, or the roll."

"Actually," offered Ophelia, "there's a really nice circle of fifths
in the third --"

"I don't caaaaaaaaaare." said Randy.

"Good. You don't care. When the fire falls from the heavens on
Judgement Day you can tell Saint Michael, in detail, all about how you
don't care." said Mom.

"Randolph," said Dad, turning off the car.

"What?"

"See over there by the overpass?"

"What, the bus stop?"

"If you'd rather not ride with us, you can take a /collectivo/. Tell
the driver you want Cenote Pacifico." He started to take out his
wallet. "Will you pass me the phrase-book, dear?"

It was very quiet, for more than a moment.

"That's what I thought," said Dad, starting the car again.

Mom played her CD.

No one said much of anything for a few minutes.

"[[https://youtu.be/D4hXJ9ax2FY?t=36][Send forth your word]]", said the CD, "Lord, and let there be light!"

/braaaaaaaaaaaaaaap/, went a noise.

"/Randy/." said Dad.

"I'm sorry, Dad, that was me." interjected Ophelia.

"Wooh, ugh." said Mom. "Beans!"

Ophelia looked embarrassed.

"No one /ever/ suspects Goodwife Two-Shoes," said Laura.

"Pull over, I think I'm going to be sick." said Mom.

Dad pulled over, and rolled down the windows.

Mom sat a while. The /song/ part of the praise and worship tape faded
into a sort of a prayerful coda. "Let mercy triumph over judgment,"
said the voice on the CD.

-----

"This is the place?" asked Ophelia.

"Sweatness!" exclaimed Laura.

"... sweatness?" asked Mom.

"Yeah. It's like saying /sweetness/, but ... hotter."

"Thank you for that... /vivid/ interjection," said Randy, still a
little subdued.

"Anytime, bro."

Randy looked around. "I don't see the beach," he noted flatly.

"We don't have a place on the beach." said Dad. "We have the nicest
place that's willing to give us a free stay while trying to convince
us to buy a timeshare."

"Watch the car for a moment," said Mom to Laura, "I'm going in to
powder my nose."

A moment passed to the 'tink. tink. tink.' sounds of a cooling engine
block.

"Thanks for, uh, covering for me," said Randy to Ophelia.

"/Randito mio/... it's like they say. /Mi madre es su madre./" offered
Ophelia.

"Yeah. It's true." said Randy. "It's true."

-----

"Cooooool." Randy gazed over the edge of a railing into the rather
large, elegantly furnished hole in the ground.

"Aquí es ... Cenote Pacifico," said Laura.

"It /is/ cool. It's connected to underground caves!" said Ophelia.

"Mmm. Natural air conditioning. I like." opined Randy.

"And it's got /shade/, so I can swim around, without turning into a
lobster!"

"Yeah, well, it's not my fault you're so..."

"White?"

"I was gonna say /Slavic/," said Randy.

"Ah. Mom's fault."

"Mmm, yes, Parental Unit Number 2."

"Parental unit ... nevermind." said Laura.

Mom was a few steps behind coming out of the lobby. "Okay, here we
go. I brought one for everybody."

"Brought one what?" asked Randy, as mom handed him a small bottle.
".... Holy water?"

"The cenote is supposed to be a portal to the /underworld./ I'm not
letting any of my children play around in a portal to the underworld
unless you bless yourself /first/. Basic parenting."

"Oh god she's serious", mumbled Randy.

"Uhh..." said Laura...

"Every time you go in," said Mom.

"Okay, I promise." said Ophelia, extracting a few drops. "I'll do it
right now."

"Mmmm. Exactly as one would expect from Princess Two-Shoes", noted
Randy.

"It won't hurt you," noted Ophelia.

"[[https://www.youtube.com/watch?v=ap_mEm8m0HU][It burnssssss us!]]" emoted Randy.


"Please, Smeagol. You've been with us how many years? If holy water
/actually/ hurt you in /any/ way, you'd have died a long, long time
ago," said Ophelia.

"Maybe I /am/ dead, and this is all just my trip to the underworld,"
suggested Randy, pointing to the cenote.

"Hmmbly," pondered Laura. "That's as good an explanation as any."

"Hey, Parental Unit 1," asked Randy, "can we go to Chicken Itza?"

"Chicken?" inquired Ophelia.

"We are not going to Chichen Itza," declared Mom.

"We're not? Would you deny our children the sight of one of the
Wonders of the World?" asked Dad, as he unlocked the room.

"Yes," declared Mom, without a moment's hesitation. "We're not here
for cultural exchange with a civilization of bloodthirsty pagans,
we're here to /relax/. Besides which, it's a four hour drive, and
I don't feel like being carsick the whole way."

"Bloodthirsty pagans," said Laura, rolling her eyes. "Gee. Tell us how
you /really/ feel."

"You know, it won't hurt you children to start caring about your own
souls for once," said Mom. "That goes double for you, little miss I'm
Eighteen Now."

"Okay, enough," interrupted Dad, loudly. "How about we figure out
rooms and relax for a bit? I'm sure we're all tired and a little
cranky."

-----

"It's still not fair that I have to sleep on the couch," complained
Randy.

"Yeah, well, you get your own room at home, you can deal with a little
inconvenience now and then," retorted Laura.

"Actually, I'm going to miss sharing with you," said Ophelia to her
sister.

"Awwwwwww," said Laura, smiling on Ophelia. "That's just 'cuz you're
so sweet."

"'Beautiful cinnamon roll too good for this world, too pure,'"
quoted Randy.

"'Look at this angelic confection!'" said Laura.

"I think you have me confused with an Onion," objected Ophelia.

"Hey Laura. When you're done smiling on your sister," said Mom, "we
can order birthday drinks."

"OooooOooOoooh," said Laura.

"Are you sure that's a good idea?" asked Dad.

"My plan is to spoil her rotten with the /good/ stuff so she'll be too
much of a liquor snob to drink anything at big campus parties," said
Mom.

"This is a silly plan," noted Laura. "I think I approve."

Dad rolled his eyes. "I think I'd best leave you /girls/ to girl
stuff."

"Same," sighed Randy. "Enjoy the corn squeezin's for me."

"But Randito, /you're/ the corniest one around," noted Laura, reaching
out for a hug.

-----

The waiter visited the table. "Another drink for you, señorita?"

"You're sure you haven't had too much?" asked Ophelia.

"We're not as think as you drunk we am," retorted Laura.

"I told you this would be better than tequila shots," said Mom.

Laura pointed to a spot on the drink menu. "How about this one?"

"I think I'll leave you guys to your booze," said Dad.

"Glorious," remarked Randy. "I'll come with."

"You all are no fun," said Laura.

The waiter left with the order.

"What did you get?" asked Mom, looking at the menu. "Wait... cinnamon?
In a cocktail??"

-----

"Blegh!" said Laura. She put down the cocktail glass.

"Told you so," said Mom.

"I /like/ cimmanum," said Ophelia, "but it's not really authentic and
Mexican. Now, really bitter chocolate, sure..."

"Never mind that," said Laura, dismissively. "I think I'm feeling
kinda... queasy."

"Are you all right?" asked Mom.

"Mmmaybe a little wobbly," said Laura. "Donde están un baños?"

"/Los baños/," corrected Ophelia. "It's in California, about halfway
up."

"You know what I mean," snapped Laura.

"Right," said Mom. "Ophelia, can you watch the stuff a moment? Your
sister may be thinker than she thought she was."

"Okay, Mom," replied Ophelia, as the pair disappeared.

Ophelia waited quietly for a moment, pondering. This corner of the dining
area was pretty empty, wasn't it? She looked for the waiter. He was
busy on the other side of the restaurant.

She looked to the left.

She looked to the right.

Then she picked up the cocktail glass, with the care and attention one
might pay to a holy relic.

"Nobody /ever/ suspects the goodwife Two-Shoes," declared the girl to
herself, quietly.

The waiter had cleared off the table before Mom got back.

** Commercial Break

/Author's note: I am unapologetic about this shift in style./
/The previous section will be edited in due course/
/and will contain additional exposition./
/In the meantime, please have these notes and this section./

/The Yucatan peninsula is made of limestone./
/Sometimes the ground gives way to reveal freshwater/
/pools that had been hidden underneath the surface./
/Some are attached to vast underwater cave systems./
/They were regarded as sacred, portals to the underworld./

Ophelia, barefoot, in naught but a nightgown, carefully opened the
door and looked out at the night.

A few moments later, she carefully closed the door.

Another pause and she carefully opened the door, again, still
barefoot, but with a handbag. This would be important. The room key
was in the handbag, and there would be no tiptoeing past her brother
on the couch to get back in if she locked herself out.

In fact, the Goodwife No-Shoes was presently regretting her little
adventure. The cinnamony cocktail had been quite large, and she was
herself fairly small, and her stomach felt queasy. And the air in the
room was quite dry, from all the air conditioning. A walk outside in
the fresh air, then, seemed just the thing. Past the nook with the
rattling ice machine, down the stairs, over by the water fountain. A
pause, for a moment, to look at the full moon. The fountain bothered
her, though. The whole time-share bothered her, as a place. It was all
over-produced, trying to project the image of Luxury without bothering
to invest in the luxuries; all veneer and no substance, which was
somehow worse than not even trying.

The cenote was real enough, at least.

She soon found herself at the top of the stairs. The cenote -- more or
less a hole in the ground, with fresh water in the bottom -- wound
their way around the walls to a little platform at the bottom, with
stairs into the water.  The water would be cool and nice. Tempting.
She took a look at the to the stairs, closed - peligro!

Closed, but not locked. Ophelia considered a moment, pondering the
merits of continuing. A thought occurred to her.  She had made a
promise to her mother about going into the water... and her little
bottle of holy water was right there, in her bag.

So she annointed herself with a few drops, made the Sign of the Cross,
and descended, being careful to hold the handrail extra-carefully, and
sat down on the edge of the platform. The water was still, like glass,
reflecting the moon. She poked at the surface of the water with her
toes, experimentally, thinking to send gentle ripples towards the
reflection.

But something unusual happened. The water was cool, as expected, but
its surface was somehow firm; it did not make way for her foot.  For a
moment she was confused: was there perhaps a rock just there under the
water? But no -- further probing showed the whole surface to be like
glass.

With a smile she stepped down onto the water, twirled about a few
times, and laughed. With cautious steps, she made her way across the
pool of water to the reflection of the moon. Then the surface of the
water glowed a pale blue, and the water surged around her like a
fountain, and the underworld took her.

-----

A number of things happened next, but they flowed from one to another
in a dream-like way, so it was hard to put them all in a definite
order. Perhaps they all happened at once. Perhaps none of them
happened at all. It is hard to say.

In one moment, she was standing on a brightly lit stage, performing a
song with her choir at school. She had a solo, and looked out at the
audience, and saw instead a field of stars. In another moment, she was
wandering through the woods behind her house - which bled into a
third, as she continued along a path surrounded by tall weeds, past an
ill-kempt railway station to the little old ballet studio. In another,
it was fall, and she had climbed the dogwood tree in her backyard, and
looked out over a sea of red leaves.

In turn they all gave way to a conversation. It was a dark place, with
stone walls, lit by dim, flaring lamps. On one side was a wide
passageway, leading around a corner, and on the wall was a large
shadow with glowing eyes and a deep, deep voice.

"What in God's name are you doing here?" asked the voice, and Ophelia
caught a glimpse of what might have been pointy teeth.

"Oh," said Ophelia, still just a little disoriented, "I suppose I'm
looking for an adventure."

"An adventure," repeated the shadow, skeptically. "In the underworld."

"It was really just a spur-of-the-moment thing," explained Ophelia,
"a once in a lifetime opportunity. How could I refuse?"

The shadow paused for a moment, perhaps considering. "Be that as it may,
this way was not meant for you. It's not too late to turn back."

"Not meant for me? Why not?" asked Ophelia.

"It just /wasn't/. For starters, your age. You are either too young,
or else far too old."

"Yeah, well, that's basically middle school, isn't it?"

"Hmmph," said the voice, and it was quiet for a while.

"So anyway, what's your name?" asked Ophelia.

"I am... /el zorro/," said the voice.

"Zorro?" said Ophelia. She immediately recalled trips to the library
with her father, renting classic black and white TV series on DVDs:
bandits, and horses, and a vigilante in a mask, ridiculously bad
swordplay... an old theme song straight out of the fifties, three
slashes with a sword.

An insight occurred to the girl, and she was quite pleased with
herself.

"... the /fox/, so cunning and free!"

"Mmm," grunted the shadow.

But Ophelia was not quite content to leave it at that. "It's a pretty
cool name, but it reminds me of hokey old television. Can I call
you Zorrito?"

"/What./"

The voice had lost some of its depth.

"... it's a diminutive?"

The shadow melted away from the wall, and from around the corner
strolled a rather ordinary-sized fox, with sandy fur. "You're in the
/underworld/, talking to a shadow easily twenty times your size, and
you decide to /name it/ with a /diminutive?/" He gave an exasperated
sigh. "Tell me, what would you have done if I had just decided to eat
you right there?"

"Holy water?"

The small fox eyed Ophelia skeptically. "Fine. You're either a born
natural, or you're quite mad. Probably both. Proceed, then, on your
adventure."

"Oh. Did I just pass some sort of a test?"

"No," said the fox, "I'm here to warn off the unqualified, and /maybe/
occasionally even eat them. You're just lucky that I'm tame."

The girl furrowed her brow. "Eating people doesn't really seem very
tame."

"It's a different matter for different people, of course," explained
the fox. "In your case, you can probably thank your mother."

"Huh." She looked at the fox, quizzically.

"Well. Weren't you going on an adventure?"

"I suppose I was!"

"Well, I'm not here to tell you what to do, but it won't be much of an
adventure if you just lurk around in the first antechamber for all
eternity. Even if you're in love with antechambers, I assure you,
we have better ones."

"Right," said Ophelia, and set off down the corridor.

-----

The path led out from behind a waterfall and across a pool as a series
of stepping-stones. The fall itself was tall and narrow, but the flow
was silky and smooth, like a dreamy long-exposure photo of falling
water, and when she passed through, it didn't feel wet, just
effervescent, and her nightgown remained dry.

She was in a narrow valley, and the sky above was lit like the surface
of the water, but with more colors. When the stepping stones ended,
she stepped out onto the water again, and walked across the
surface. Her braid had come undone in the waterfall, and her hair
trailed back behind her as she walked, as if she was underwater.

Zorrito, not far behind, sat down on the surface of the water, and
floated along behind. Soon, they arrived at a great edifice,
stretching across the valley, with grand doors that were probably
taller than her house, all inscribed with a language she didn't
understand.

"It's not very Aztec, is it?" asked Ophelia, taking stock of the place.

"Of course it isn't," said Zorro.

"Why not?"

"You yourself are of mixed Slavic and English heritage, and Christian
upbringing. You are staying in Mexico, yes, but at a cenote long
abandoned by the native population, in a hotel constructed by a
post-colonial, mestizo labor force, on behalf of a Delaware
corporation. But even aside from all this, even we were at Chichen
Itza itself during the heyday of the indigenous peoples of the Yucatan
peninsula, it would not have been Aztec" said the fox, pausing a
moment for special emphasis, "because they were /Mayans./"

"Oh," said Ophelia, abashed. She looked up at the doors, a deep black,
lettering inlaid with silver. The door handles were well above her
head.

She puzzled about that for a bit, to distract herself from her
mistake.

Zorrito yawned, covering his mouth with a paw.

"Well, I suppose the simple things are always worth a try," said
Ophelia. She knocked; the doors were opened unto her.

-----

"This is, of course, /all your fault./"

"I love it!" said Ophelia.

"This is because you are a ridiculous, silly girl," said Zorrito.

"I will admit to that," said Ophelia.

The doors had opened into a long, open space, lined with columns and
arches. It was very much like a cathedral, except that a stream of
water flowed down the center, and the roof was too high to see, and
the chapels off to the side and the stained glass windows were a
little bit different.

"Well. Who is it?" asked Zorrito, resigned to an explanation.

"It's /Magical Slayer Mamika/," said Ophelia. "She's really cute, and
does this super cool ultimate /Magical Splash Flare/."

The fox examined the runes skeptically. "And she uses this...
/orbital bombardment/ ... to make friends."

Ophelia nodded. "Yep. It's a /classic/. Look! The heart on her wand is
sparkling."

The fox, slightly bored, wandered on to the next little nook, and set
about reading, while Ophelia marvelled at the glasswork.

Suddenly, there was a sputtering, choking noise. "What ... what,
in the name of all that is holy??" shouted Zorrito.

Ophelia ducked her head around the corner. "Oh! The Fire Sisters!"

"You /watched/ this?" he asked. "At /your/ age?"

"Oh. Laura made me skip one episode."

"You don't say," said the fox, glaring at the text beneath a window.

"Hey, Karen is cool. Honorary magical girl for sure, and she does
everything without magic. She's a real Ally of Justice with a song
about it and everything."

"Uh-huh," said the fox. "And that would be why the incense smells like
marshmallows, I suppose."

"Marshmallows /of justice/."

"I have my concerns," declared the fox.

-----

At the transept, where the long hall of the sanctuary crossed with a
short one, the stream of water branched off to the right, coursing
down a few steps. Above this, in place of a tabernacle, or an altar,
where the great cross might hang, there floated instead an image of a
lady in white, with golden eyes and pink hair. Her dress was short in
front, but long in the back, and on its inside shone the stars and the
cosmos.

Ophelia looked at the figure, askance.

"Your thoughts?" inquired the fox.

"I think ... I think I've seen her before, and this is spoilers."

"That'd be one word for it."

"Who is she?"

"Hope," said the fox.

Ophelia spent a few moments in contemplation, feeling a certain
gravity to the situation.

"I like this place," she said; "I like it a lot, but what is it all
here for?"

"For the vigil, of course."

"How's that, now?"

"It's traditional, for knights. Cleansing. Vigil. The white robe, to
symbolize purity."

"It's really more of a nightgown, though."

"Notwithstanding. That is the dream, correct? To be a knight?"

"Oh. Uh, not exactly?"

"A knight, in the service of Justice."

"Maybe?"

"Basically that."

"I don't like swords, though."

"No, of course not," said Zorrito, "you like /ballerinas/, which is
why you spent something like six hours watching the duck princess over
there." He glanced at a nearby nook.

"It was beautiful! It was /irresistible/. It was like someone cast a
magic spell and gave the show a real animation budget! I wish I could
move like that."

"Uh-huh. And how much did you watch?"

"Just ... the first season."

"And how many episodes was that, again?"

"Fine," said Ophelia. "/Five and a half/ hours."

"I was quite productive. Plotted an appropriate revenge. But Magical
Slayer Mamika got jealous. I heard her crying."

"Ha ha."

"So there's your vigil, at least. Are you on the adventure train or
are you off?"

"I'm ... going to consider the subject with the appropriate gravity."

"I'd settle for /some/ of the appropriate gravity. This is /justice/
we're talking about."

-----

Ophelia found Justice not far off the transept, overlooking a
reflecting pool at what seemed to be the end of the stream. It was a
classical rendition -- grey stone, blindfold, sword in the right hand,
balance in the left -- and quite tall, many times taller than the girl.

At the foot of the statue were two neatly folded garments.

"What's this?" asked Ophelia.

"Robes. You put them on."

"And take off my nightgown?"

"No. On top. The red one first, then pink."

"Why red first?"

"Well normally, you'd have a /black/ robe on the outside, as a symbol
of being willing to die for your feudal lord. It's not really
genre-appropriate here, though."

She donned the robes.

"Do you suppose," asked Zorro, "that you are truly ready to be a
faithful ally of justice?" asked Zorrito. "Do you know what this would
mean?"

"I'm ... not sure," admitted Ophelia.

"This path was not meant for you," said the fox. "Would you take it
anyway, commit to pay any price, without knowing what it may be, only
that it is right?"

"I think ... I think I can do that, yes," said the girl. "If it's
really, truly right."

"What do you suppose it takes to serve justice?" asked the fox. "Don't
answer that right away. Think on it a while."

She sat, thinking about it. A gentle ripple on the surface of the pool
caught her eye, and she turned to look at the pool.

A reflection looked back at her. It was not her own, but it might have
been her dream. A magical girl - a ballerina, perhaps - with bare
shoulders, red hair, tied back in an elegant bun, woven through with a
white ribbon, like icing on a cinnamon roll. But Ophelia's gaze was
drawn inexorably to the eyes: blue eyes, like her own, almost
comically big. Her expression was gentle, achingly beautiful, and yet
terrifying, for it felt to Ophelia as if her soul had been laid bare,
and it was very, very small.

She rose, slowly, so as not to break the gaze.

"I think," she said, "that to serve justice, one of the things you
need, one of the most important things, would have to be
understanding.  And that... that is something that I don't have a lot
of. I tell myself I know pretty well what's right and wrong, but there
are a lot of complicated things in the world where it's easy to lose
sight of that." She turned to look at Zorrito. "You might be right. I
might not be old enough, after all. Being an ally of justice is part
of my dream, but a lot of that is really just just a dream for me,
wanting to be cool. I'd probably do a terrible job. I don't think I'd
deserve it."

"Understanding is important," said the fox. "But understanding can be
grown, with experience. More important by far, and much harder to
teach or to grow, are the virtues of humility, and a pure heart, for
they will lead one to seek out that understanding which one does not
have." He paused, and turned to the statue. "I think she'll do fine."

The statue moved, sticking the tip of its sword in the ground, and,
with a right hand almost as tall as Ophelia herself, ever-so-gently
pushed the girl backwards into the pool.

-----

For a short eternity, in a space between worlds, Ophelia danced.

-----

*End Episode 1*
